// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: notice.proto

package server

import (
	"context"

	"notice/rpc/internal/logic"
	"notice/rpc/internal/svc"
	"notice/rpc/notice/notice"
)

type NoticeServiceServer struct {
	svcCtx *svc.ServiceContext
	notice.UnimplementedNoticeServiceServer
}

func NewNoticeServiceServer(svcCtx *svc.ServiceContext) *NoticeServiceServer {
	return &NoticeServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *NoticeServiceServer) Notice(ctx context.Context, in *notice.NoticeRequest) (*notice.NoticeResponse, error) {
	l := logic.NewNoticeLogic(ctx, s.svcCtx)
	return l.Notice(in)
}
